openapi: 3.0.3
info:
  title: Example API
  version: 1.0.0
components:
  securitySchemes:
    oAuthSample:   
      type: oauth2
      description: Lorem Ipsum
      flows:
        authorizationCode:
          authorizationUrl: https://localhost:8443/dev/oauth/authorize
          tokenUrl: https://localhost:8443/dev/oauth/token
          scopes:
            read: Read user information
            
security:
  - oAuthSample:
    - read
# individual operations - dummy
paths:
  /pets:
    post:
      summary: Add a new pet
      security:
        - oAuthSample:
          - read
      responses:
        '201':
          description: Success
    